services:
# MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:6.0.14
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog

# OpenSearch: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    volumes:
      - os_data:/usr/share/opensearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "OPENSEARCH_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: "on-failure"
    mem_limit: 8g
    networks:
      - graylog

# Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:6.0.3
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
    # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=<REPLACE_ME>
    # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=<REPLACE_ME>
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/config/node-id
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - opensearch
    restart: always
    depends_on:
      - mongodb
      - opensearch
    ports:
    # Graylog web interface and REST API
      - 9000:9000
    # Syslog TCP
      - 1514:1514
    # Syslog UDP
      - 1514:1514/udp
    # GELF TCP
      - 12201:12201
    # GELF UDP
      - 12201:12201/udp
    networks:
      - graylog

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
  os_data:
    driver: local
  graylog_data:
    driver: local

networks:
  graylog:
    driver: bridge